"""
SARGE - Single-Model Adaptive Routing & Generation Engine
Schemas and type definitions
"""
from typing import TypedDict, List, Optional, Literal
from pydantic import BaseModel, Field


class AgentState(TypedDict):
    """Global state for SARGE workflow"""
    raw_input: str
    router_decision: str  # 'chat', 'generate', 'refine', 'unknown'
    router_confidence: float        # NEW: Confidence score from router
    prospect_data: Optional[dict]
    strategy_brief: Optional[dict]  # NEW: Hyperpersonalization strategy
    retrieved_templates: List[str]  # NEW: RAG context (past successful emails)
    critic_feedback: Optional[dict] # NEW: Structured feedback
    generation_attempts: int        # NEW: Track self-correction loops
    rag_context: List[str]
    requested_channels: List[str]   # NEW: Channels requested by user (email, linkedin, whatsapp)
    news_context: Optional[str]     # NEW: News jacking context (DDG search results)
    writing_style: Optional[dict]   # NEW: Inferred writing style (rules + examples)
    generated_content: dict
    conversation_history: List[dict]


class RouterOutput(BaseModel):
    """Output from Router node - strict JSON classification"""
    destination: Literal["chat", "generate", "refine", "unknown"] = Field(
        description="The routing destination based on intent classification"
    )
    confidence: float = Field(
        ge=0.0, le=1.0,
        description="Confidence score for the routing decision"
    )
    reasoning: str = Field(
        description="Brief explanation of why this route was chosen"
    )


class ProspectProfile(BaseModel):
    """Structured prospect data extracted by Analyst preset"""
    name: Optional[str] = Field(default="Unknown", description="Full name of the prospect")
    role: Optional[str] = Field(None, description="Job title or role")
    industry: Optional[str] = Field(None, description="Industry or sector")
    company: Optional[str] = Field(None, description="Company name")
    detected_tone: Optional[Literal["casual", "formal", "technical"]] = Field(
        default="formal",
        description="Detected communication tone from profile"
    )
    key_interests: List[str] = Field(
        default_factory=list,
        description="Key topics or interests mentioned"
    )
    research_queries: List[str] = Field(
        default_factory=list,
        description="Specific technical topics or search queries to research (e.g., ['CUDA-X edge optimization', 'NVIDIA earnings 2026'])"
    )


class GeneratedContent(BaseModel):
    """Multi-channel generated outreach content"""
    email: Optional[str] = Field(None, description="Cold email content")
    linkedin: Optional[str] = Field(None, description="LinkedIn DM (max 300 chars)")
    whatsapp: Optional[str] = Field(None, description="WhatsApp message")
    audio_path: Optional[str] = Field(None, description="Path to the generated audio version of the outreach")


class StrategyBrief(BaseModel):
    """Hyperpersonalized outreach strategy generated by Strategist"""
    hook: str = Field(description="The 'hook' or personalized opener based on research")
    value_prop: str = Field(description="Personalized value proposition for this specific prospect")
    pain_point: str = Field(description="Potential pain point to address")
    recommended_tone: str = Field(description="Nuanced tone recommendation")


class CriticFeedback(BaseModel):
    """Feedback from Critic node for self-correction"""
    score: int = Field(ge=1, le=10, description="OVERALL QUALITY SCORE (1-10). Mandatory field.")
    channel_scores: Optional[dict] = Field(default={}, description="Specific scores per channel (e.g. {'email': 9, 'linkedin': 5})")
    critique: str = Field(description="Detailed feedback on how to improve the outreach")
    additions: List[str] = Field(default_factory=list, description="Specific phrases or details to ADD for hyperpersonalization")
    removals: List[str] = Field(default_factory=list, description="Specific phrases or sections to REMOVE")
    is_ready: bool = Field(description="Whether the content is ready for the user (score >= 8 or all channels valid)")
